Provide temperature compensation #84
adafruit/Adafruit_BME280_Library pull request #85
Opened 2020-08-02 06:27 UTC by AgentZombie

### Scope

A private member field is added to the class ` Adafruit_BME280`: `float t_fine_adjust`

### Limitations

A few degrees Celsius of temperature compensation result in only tiny changes in pressure and humidity.

```
Adjustment: 3
28.66 - 100066.50 - 30.76
Adjustment: 0
25.65 -- 99553.88 - 30.81
Adjustment: 3
28.71 - 100069.04 - 32.90
Adjustment: 0
25.73 -- 99555.32 - 34.43
```

Running:
```
#include <Arduino.h>
#include <Wire.h>
#include <SPI.h>
#include <Adafruit_Sensor.h>
#include <Adafruit_BME280.h>

Adafruit_BME280 bme; // I2C

void setup() {
  Serial.begin(9600);
  if (! bme.begin(BME280_ADDRESS_ALTERNATE, &Wire)) {
    Serial.println("badness");
    while(1);
  }
  // bme.setTemperatureAdjustment(3);
}

void loop() {
  bme.setTemperatureAdjustment(3);
  Serial.println("Adjustment: 3");
  Serial.print(bme.readTemperature());
  Serial.print(" - ");
  Serial.print(bme.readPressure());
  Serial.print(" - ");
  Serial.println(bme.readHumidity());
  delay(1000);
  bme.setTemperatureAdjustment(0);
  Serial.println("Adjustment: 0");
  Serial.print(bme.readTemperature());
  Serial.print(" -- ");
  Serial.print(bme.readPressure());
  Serial.print(" - ");
  Serial.println(bme.readHumidity());
  delay(5000);
}
```

2020-08-02 06:28 UTC, AgentZombie commented
Bah, I didn't write the getter. Stand by.

2020-08-02 06:36 UTC, AgentZombie commented
Fixed

2020-08-02 14:31 UTC, ladyada commented
nice, thank you :) can you change the name to xetTemperatureOffset or xetTemperatureCorrection, we think that might be easier to recognize

2020-08-03 00:41 UTC, AgentZombie commented
Done.

I notice you're reviewing and commenting on Saturday and Sunday. I hope you take days off.

2020-08-03 01:43 UTC, ladyada commented
thanx - next up can you run `clang-format -i` on the files youve changed (or hand-adapt these diffs)
https://github.com/adafruit/Adafruit_BME280_Library/runs/938637551#step:7:1

2020-08-03 03:20 UTC, AgentZombie commented
Done! I appreciate your time.

2020-08-03 13:47 UTC, ladyada requested changes
one more small change!

2020-08-03 13:47 UTC, ladyada commented on Adafruit_BME280.h
> +  int32_t t_fine_adjust; //!< add to compensate temp readings and in turn to
please initialize to 0

2020-08-03 20:58 UTC, AgentZombie commented
Done!

2020-08-03 21:20 UTC, ladyada requested changes

2020-08-03 21:20 UTC, ladyada commented on Adafruit_BME280.cpp
> + *  @params  adjustment  Value to be added to each tempature reading in Celcius
change from `@params` to `@param`

2020-08-04 06:22 UTC, AgentZombie commented
Fixed!

2020-08-04 13:45 UTC, ladyada commented
awesome, its now passing CI - good work!

2020-08-04 13:45 UTC, merged